### ISSUE TITLE
Create config.json file

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-algorithm#10]
### Tasks 
- [x] create confit files with 3 templates: $25K / $50K / $100K 
- [x] store *ALL* algorithm variables in a `config.json' file
 - [x] Python file skinning, renaming, re-binning into fewer folders
 - [x] refactor Python unit tests @irene-bbox (both Coinbase and Plaid)
