### ISSUE TITLE
Integrate with CovalentHQ

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-algorithm#12]
### Tasks

- [x] integrate with the CovalentHQ API (use the Python library `fastapi`)
- [x] trade from your MetaMask wallet to create some transaction activity and data to then export and manipulate
- [x] fetch data from your ETH wallet address via `fastapi`
- [x] understand data structures and format transaction data
