### ISSUE TITLE
Algorithms Optimization

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/near-oracle-algorithm#3]
#### Description
Does the credit scoring algorithm initially develop for the SCRTsibyl DApp perform identically when executed for the NEARoracle DApp?

#### Tasks
 - [x] test run the algorithm (1) on *dummy data*
 - [x] test run the algorithm (2) via Coinbase HQ integration
 - [x] test run the algorithm (3) from front-end *DApp* on testnet
 - [x] add execution body to the 3 functions you'll invoke for the **KYC-only** template
